[package]
name = "slang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.0"
strum = "0.24.1"
strum_macros = "0.24.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
